name: Run Turbo.az Scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (adjust as needed)
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scraper
      run: python main.py
    
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: scraper-logs
        path: logs/
    
    - name: Upload data
      uses: actions/upload-artifact@v2
      with:
        name: scraped-data
        path: data/
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/cars.db
        git add data/turbo_az_listings.csv
        git commit -m "Update scraped data" || echo "No changes to commit"
        git push
